### ISSUE TITLE
Module is not defined

### ISSUE THREAD

**Issue by eurolife** [rainjay/pagination#1]
I'm getting these errors:

Uncaught ReferenceError: module is not defined
    at index.js:1
(anonymous) @ index.js:1
pagination.html:194 Uncaught TypeError: Cannot read property 'displayHTMLCode' of undefined
    at HTMLDocument.<anonymous> (pagination.html:194)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at Function.ready (jquery.js:3536)
    at HTMLDocument.completed (jquery.js:3552)

Is it because I am not using 'require'? I don't use require only JQuery. Any examples without needing to use 'require'?

**Comment by wang2lang** [comment]
js-pagination is implemented in CommonJs, so you need to use it with some tools like webpack and require js-pagination in your codes.  but you can copy codes in dist/index.js and replace `module.exports=Pagination;` with `window.Pagination = Pagination;` without needing to use 'require'
